sudo: required
dist: trusty
language: python
python:
- '3.4'
before_install:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -qq
- sudo apt-get install armake python3-pip -y
- sudo pip3 install sqflint
install: true
script:
- make
- make test
notifications:
  email:
    on_success: never
    on_failure: change
